// <auto-generated />
using Blogrolling.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blogrolling.Migrations
{
    [DbContext(typeof(BlogrollingContext))]
    [Migration("20231209121526_FixDefaultValue")]
    partial class FixDefaultValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Blogrolling.Database.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("博客ID");

                    b.Property<string>("Author")
                        .HasColumnType("longtext")
                        .HasComment("博客作者");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasComment("博客简介");

                    b.Property<string>("Feed")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Feed");

                    b.Property<long>("FeedNextUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasComment("下次Feed更新时间");

                    b.Property<long>("FeedPrevUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasComment("上次Feed更新时间");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("博客标志");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("博客链接");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("博客名称");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("Ok")
                        .HasComment("博客状态");

                    b.HasKey("Id");

                    b.ToTable("Blog", t =>
                        {
                            t.HasComment("博客数据源");
                        });
                });

            modelBuilder.Entity("Blogrolling.Database.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("文章ID");

                    b.Property<int>("BlogId")
                        .HasColumnType("int")
                        .HasComment("博客ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("文章介绍");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("文章GUID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("文章标题");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("Post", t =>
                        {
                            t.HasComment("博客文章");
                        });
                });

            modelBuilder.Entity("Blogrolling.Database.PostTag", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasComment("文章ID");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasComment("标签ID");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTag", t =>
                        {
                            t.HasComment("文章标签");
                        });
                });

            modelBuilder.Entity("Blogrolling.Database.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("标签Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tag", t =>
                        {
                            t.HasComment("标签");
                        });
                });

            modelBuilder.Entity("Blogrolling.Database.Post", b =>
                {
                    b.HasOne("Blogrolling.Database.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Blogrolling.Database.PostTag", b =>
                {
                    b.HasOne("Blogrolling.Database.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blogrolling.Database.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Blogrolling.Database.Blog", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Blogrolling.Database.Post", b =>
                {
                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("Blogrolling.Database.Tag", b =>
                {
                    b.Navigation("PostTags");
                });
#pragma warning restore 612, 618
        }
    }
}
